apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suse-demo
resources:
- configs/source-vars.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: suse-demo-config
  env: configs/env.txt
images:
- name: paulofrazao/suse-demo-yellow
  newName: paulofrazao/suse-demo-yellow
  newTag: 0.1.0
commonLabels:
  app.kubernetes.io/name: suse-demo
vars:
- fieldref:
    fieldPath: data.MY_NAMESPACE
  name: MY_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
- fieldref:
    fieldPath: data.URL_HOST
  name: URL_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- kustomize-config.yaml

